package com.bing.model;

import java.util.Date;

public class PeopleModel {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column people.id
	 * @mbggenerated  Mon Apr 25 19:17:18 CST 2016
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column people.age
	 * @mbggenerated  Mon Apr 25 19:17:18 CST 2016
	 */
	private Integer age;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column people.created_time
	 * @mbggenerated  Mon Apr 25 19:17:18 CST 2016
	 */
	private Date createdTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column people.name
	 * @mbggenerated  Mon Apr 25 19:17:18 CST 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column people.update_time
	 * @mbggenerated  Mon Apr 25 19:17:18 CST 2016
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column people.id
	 * @return  the value of people.id
	 * @mbggenerated  Mon Apr 25 19:17:18 CST 2016
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column people.id
	 * @param id  the value for people.id
	 * @mbggenerated  Mon Apr 25 19:17:18 CST 2016
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column people.age
	 * @return  the value of people.age
	 * @mbggenerated  Mon Apr 25 19:17:18 CST 2016
	 */
	public Integer getAge() {
		return age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column people.age
	 * @param age  the value for people.age
	 * @mbggenerated  Mon Apr 25 19:17:18 CST 2016
	 */
	public void setAge(Integer age) {
		this.age = age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column people.created_time
	 * @return  the value of people.created_time
	 * @mbggenerated  Mon Apr 25 19:17:18 CST 2016
	 */
	public Date getCreatedTime() {
		return createdTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column people.created_time
	 * @param createdTime  the value for people.created_time
	 * @mbggenerated  Mon Apr 25 19:17:18 CST 2016
	 */
	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column people.name
	 * @return  the value of people.name
	 * @mbggenerated  Mon Apr 25 19:17:18 CST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column people.name
	 * @param name  the value for people.name
	 * @mbggenerated  Mon Apr 25 19:17:18 CST 2016
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column people.update_time
	 * @return  the value of people.update_time
	 * @mbggenerated  Mon Apr 25 19:17:18 CST 2016
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column people.update_time
	 * @param updateTime  the value for people.update_time
	 * @mbggenerated  Mon Apr 25 19:17:18 CST 2016
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}